INSERT INTO `qb_hook_plugin` (`id`, `hook_key`, `plugin_key`, `hook_class`, `about`, `ifopen`, `list`, `author`, `author_url`, `version`, `version_id`) VALUES(0, 'user_leave', '', 'app\\qun\\hook\\Content', '直播课堂观看时间统计', 1, 0, '', '', '', 0);

DROP TABLE IF EXISTS `qb_qun_order`;
CREATE TABLE IF NOT EXISTS `qb_qun_order` (
  `id` mediumint(7) NOT NULL AUTO_INCREMENT,
  `uid` mediumint(7) NOT NULL COMMENT '购买者UID',
  `aid` mediumint(7) NOT NULL COMMENT '使用的圈子ID',
  `timelong` mediumint(7) NOT NULL COMMENT '购买总时长(秒)',
  `usetime` mediumint(7) NOT NULL COMMENT '已使用时间(秒)',
  `create_time` int(10) NOT NULL COMMENT '购买时间',
  PRIMARY KEY (`id`),
  KEY `uid` (`uid`),
  KEY `aid` (`aid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COMMENT='会员课堂(直播)时长购买订单' AUTO_INCREMENT=1 ;


INSERT INTO `qb_qun_field` (`id`, `name`, `title`, `type`, `field_type`, `value`, `options`, `about`, `show`, `mid`, `ajax_url`, `next_items`, `param`, `format`, `table`, `level`, `key`, `option`, `pid`, `list`, `listshow`, `ifsearch`, `ifmust`, `nav`, `input_width`, `input_height`, `unit`, `match`, `css`, `script`, `trigger`, `range_opt`, `group_view`, `index_hide`) VALUES(0, 'minute_money', '课堂时长收费', 'money', 'decimal(6,2) unsigned NOT NULL', '', '', '每分钟,单位(元)，VIP会员免费观看，不设置所有用户都免费收看', 1, 1, '', '', '', '', '', 2, '', '', '', 0, 0, 0, 0, '权限设置', '', '', '', '', '', '', '', '', '', 1);
INSERT INTO `qb_qun_field` (`id`, `name`, `title`, `type`, `field_type`, `value`, `options`, `about`, `show`, `mid`, `ajax_url`, `next_items`, `param`, `format`, `table`, `level`, `key`, `option`, `pid`, `list`, `listshow`, `ifsearch`, `ifmust`, `nav`, `input_width`, `input_height`, `unit`, `match`, `css`, `script`, `trigger`, `range_opt`, `group_view`, `index_hide`) VALUES(0, 'free_time', '课堂试看时长', 'number', 'mediumint(7) NOT NULL DEFAULT ''0''', '10', '', '单位分钟,为0或者不设置的话,即代表不给试看', 1, 1, '', '', '', '', '', 2, '', '', '', 0, 0, 0, 0, '权限设置', '', '', '', '', '', '', '', '', '', 1);
ALTER TABLE  `qb_qun_content1` ADD  `minute_money` DECIMAL( 6, 2 ) NOT NULL COMMENT  '课堂时长收费',ADD  `free_time` MEDIUMINT( 7 ) NOT NULL COMMENT  '课堂试看时长';

INSERT INTO `qb_qun_field` (`id`, `name`, `title`, `type`, `field_type`, `value`, `options`, `about`, `show`, `mid`, `ajax_url`, `next_items`, `param`, `format`, `table`, `level`, `key`, `option`, `pid`, `list`, `listshow`, `ifsearch`, `ifmust`, `nav`, `input_width`, `input_height`, `unit`, `match`, `css`, `script`, `trigger`, `range_opt`, `group_view`, `index_hide`) VALUES(0, 'minute_money', '课堂时长收费', 'money', 'decimal(6,2) unsigned NOT NULL', '', '', '每分钟,单位(元)，VIP会员免费观看，不设置所有用户都免费收看', 1, 2, '', '', '', '', '', 2, '', '', '', 0, 0, 0, 0, '权限设置', '', '', '', '', '', '', '', '', '', 1);
INSERT INTO `qb_qun_field` (`id`, `name`, `title`, `type`, `field_type`, `value`, `options`, `about`, `show`, `mid`, `ajax_url`, `next_items`, `param`, `format`, `table`, `level`, `key`, `option`, `pid`, `list`, `listshow`, `ifsearch`, `ifmust`, `nav`, `input_width`, `input_height`, `unit`, `match`, `css`, `script`, `trigger`, `range_opt`, `group_view`, `index_hide`) VALUES(0, 'free_time', '课堂试看时长', 'number', 'mediumint(7) NOT NULL DEFAULT ''0''', '10', '', '单位分钟,为0或者不设置的话,即代表不给试看', 1, 2, '', '', '', '', '', 2, '', '', '', 0, 0, 0, 0, '权限设置', '', '', '', '', '', '', '', '', '', 1);
ALTER TABLE  `qb_qun_content2` ADD  `minute_money` DECIMAL( 6, 2 ) NOT NULL COMMENT  '课堂时长收费',ADD  `free_time` MEDIUMINT( 7 ) NOT NULL COMMENT  '课堂试看时长';

INSERT INTO `qb_qun_field` (`id`, `name`, `title`, `type`, `field_type`, `value`, `options`, `about`, `show`, `mid`, `ajax_url`, `next_items`, `param`, `format`, `table`, `level`, `key`, `option`, `pid`, `list`, `listshow`, `ifsearch`, `ifmust`, `nav`, `input_width`, `input_height`, `unit`, `match`, `css`, `script`, `trigger`, `range_opt`, `group_view`, `index_hide`) VALUES(0, 'minute_money', '课堂时长收费', 'money', 'decimal(6,2) unsigned NOT NULL', '', '', '每分钟,单位(元)，VIP会员免费观看，不设置所有用户都免费收看', 1, 3, '', '', '', '', '', 2, '', '', '', 0, 0, 0, 0, '权限设置', '', '', '', '', '', '', '', '', '', 1);
INSERT INTO `qb_qun_field` (`id`, `name`, `title`, `type`, `field_type`, `value`, `options`, `about`, `show`, `mid`, `ajax_url`, `next_items`, `param`, `format`, `table`, `level`, `key`, `option`, `pid`, `list`, `listshow`, `ifsearch`, `ifmust`, `nav`, `input_width`, `input_height`, `unit`, `match`, `css`, `script`, `trigger`, `range_opt`, `group_view`, `index_hide`) VALUES(0, 'free_time', '课堂试看时长', 'number', 'mediumint(7) NOT NULL DEFAULT ''0''', '10', '', '单位分钟,为0或者不设置的话,即代表不给试看', 1, 3, '', '', '', '', '', 2, '', '', '', 0, 0, 0, 0, '权限设置', '', '', '', '', '', '', '', '', '', 1);
ALTER TABLE  `qb_qun_content3` ADD  `minute_money` DECIMAL( 6, 2 ) NOT NULL COMMENT  '课堂时长收费',ADD  `free_time` MEDIUMINT( 7 ) NOT NULL COMMENT  '课堂试看时长';

INSERT INTO `qb_qun_field` (`id`, `name`, `title`, `type`, `field_type`, `value`, `options`, `about`, `show`, `mid`, `ajax_url`, `next_items`, `param`, `format`, `table`, `level`, `key`, `option`, `pid`, `list`, `listshow`, `ifsearch`, `ifmust`, `nav`, `input_width`, `input_height`, `unit`, `match`, `css`, `script`, `trigger`, `range_opt`, `group_view`, `index_hide`) VALUES(0, 'minute_money', '课堂时长收费', 'money', 'decimal(6,2) unsigned NOT NULL', '', '', '每分钟,单位(元)，VIP会员免费观看，不设置所有用户都免费收看', 1, 4, '', '', '', '', '', 2, '', '', '', 0, 0, 0, 0, '权限设置', '', '', '', '', '', '', '', '', '', 1);
INSERT INTO `qb_qun_field` (`id`, `name`, `title`, `type`, `field_type`, `value`, `options`, `about`, `show`, `mid`, `ajax_url`, `next_items`, `param`, `format`, `table`, `level`, `key`, `option`, `pid`, `list`, `listshow`, `ifsearch`, `ifmust`, `nav`, `input_width`, `input_height`, `unit`, `match`, `css`, `script`, `trigger`, `range_opt`, `group_view`, `index_hide`) VALUES(0, 'free_time', '课堂试看时长', 'number', 'mediumint(7) NOT NULL DEFAULT ''0''', '10', '', '单位分钟,为0或者不设置的话,即代表不给试看', 1, 4, '', '', '', '', '', 2, '', '', '', 0, 0, 0, 0, '权限设置', '', '', '', '', '', '', '', '', '', 1);
ALTER TABLE  `qb_qun_content4` ADD  `minute_money` DECIMAL( 6, 2 ) NOT NULL COMMENT  '课堂时长收费',ADD  `free_time` MEDIUMINT( 7 ) NOT NULL COMMENT  '课堂试看时长';

INSERT INTO `qb_qun_field` (`id`, `name`, `title`, `type`, `field_type`, `value`, `options`, `about`, `show`, `mid`, `ajax_url`, `next_items`, `param`, `format`, `table`, `level`, `key`, `option`, `pid`, `list`, `listshow`, `ifsearch`, `ifmust`, `nav`, `input_width`, `input_height`, `unit`, `match`, `css`, `script`, `trigger`, `range_opt`, `group_view`, `index_hide`) VALUES(0, 'minute_money', '课堂时长收费', 'money', 'decimal(6,2) unsigned NOT NULL', '', '', '每分钟,单位(元)，VIP会员免费观看，不设置所有用户都免费收看', 1, 5, '', '', '', '', '', 2, '', '', '', 0, 0, 0, 0, '权限设置', '', '', '', '', '', '', '', '', '', 1);
INSERT INTO `qb_qun_field` (`id`, `name`, `title`, `type`, `field_type`, `value`, `options`, `about`, `show`, `mid`, `ajax_url`, `next_items`, `param`, `format`, `table`, `level`, `key`, `option`, `pid`, `list`, `listshow`, `ifsearch`, `ifmust`, `nav`, `input_width`, `input_height`, `unit`, `match`, `css`, `script`, `trigger`, `range_opt`, `group_view`, `index_hide`) VALUES(0, 'free_time', '课堂试看时长', 'number', 'mediumint(7) NOT NULL DEFAULT ''0''', '10', '', '单位分钟,为0或者不设置的话,即代表不给试看', 1, 5, '', '', '', '', '', 2, '', '', '', 0, 0, 0, 0, '权限设置', '', '', '', '', '', '', '', '', '', 1);
ALTER TABLE  `qb_qun_content5` ADD  `minute_money` DECIMAL( 6, 2 ) NOT NULL COMMENT  '课堂时长收费',ADD  `free_time` MEDIUMINT( 7 ) NOT NULL COMMENT  '课堂试看时长';

